//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DovizKurlari
    {
        public int id { get; set; }
        public Nullable<int> Tur { get; set; }
        public string Adi { get; set; }
        public string Kod { get; set; }
        public string DovizAlis { get; set; }
        public string DovizSatis { get; set; }
        public string EfektifAlis { get; set; }
        public string EfektifSatis { get; set; }
        public string Tarih { get; set; }
        public string YapiKrediAlis { get; set; }
        public string YapiKrediSatis { get; set; }
        public string COGNISA { get; set; }
        public string COGNISS { get; set; }
        public string Guncelleyen { get; set; }
        public string GuncellemeTarihi { get; set; }
    }
}
